---
# Downloads
- name: Download Dgraph Installation Script
  get_url:
    url: "https://get.dgraph.io"
    dest: /tmp/get-dgraph.sh
    mode: 0755

# Runs the previously downloaded script
- name: Install Dgraph
  shell: "/tmp/get-dgraph.sh"
  become: yes

# Starts a Dgraph Zero instance
- name: Run Dgraph Zero
  shell: 'nohup {{ dgraph_zero_command }} >> {{ dgraph_zero_log_path }} 2>&1&'

# Verifies that Dgraph Zero is listening to requests
- name: Check Dgraph Zero success
  wait_for:
    port: 5080
    delay: {{ service_verification_delay }}
    timeout: {{ service_verification_timeout }}

# Starts a Dgraph Server instance
- name: Run Dgraph Server
  shell: 'nohup {{ dgraph_server_command }} >> {{ dgraph_server_log_path }} 2>&1&'

# Verifies that Dgraph Server is listening to requests
- name: Check Dgraph Server success
  wait_for:
    port: 8080
    delay: {{ service_verification_delay }}
    timeout: {{ service_verification_timeout }}

#  Starts a Dgraph Ratel instance
- name: Run Dgraph Ratel
  shell: "nohup {{ dgraph_ratel_command }} >> {{ dgraph_ratel_log_path }} 2>&1&"

# Verifies that Dgraph Ratel is listening to requests
- name: Wait 60 seconds for port 8000 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 8000
    delay: {{ service_verification_delay }}
    timeout: {{ service_verification_timeout }}
