---
- name: Download Dgraph Installation Script 
  get_url:
    url: "https://get.dgraph.io"
    dest: /tmp/get-dgraph.sh
    mode: 0755
  become: yes

- name: Install Dgraph
  shell: "/tmp/get-dgraph.sh"
  become: yes

- name: Run Dgraph Zero
  shell: "nohup dgraph zero --bindall=true --idx 1 -w wz  > /vagrant_data/dgraph-zero.log &"
  become: yes

- name: Wait 60 seconds for port 5080 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 5080
    delay: 10
    timeout: 60

- name: Run Dgraph Server
  shell: "nohup dgraph server --lru_mb 1024 > /vagrant_data/dgraph-server.log &"
  become: yes

- name: Run Dgraph Ratel
  shell: "nohup dgraph-ratel > /vagrant_data/dgraph-ratel.log &"
  become: yes

- name: Wait 60 seconds for port 8000 to become open on the host, don't start checking for 10 seconds
  wait_for: 
    port: 8000
    delay: 10
    timeout: 60